//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMCompare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ORMCompare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE SP_DeleteAllDepartmentEmployees
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    -- Insert statements for procedure here
        ///	BEGIN TRANSACTION;
        ///	Delete from DepartmentEmployees
        ///	COMMIT TRANSACTION
        ///END
        ///GO
        ///.
        /// </summary>
        internal static string SP_DeleteAllDepartmentEmployees {
            get {
                return ResourceManager.GetString("SP_DeleteAllDepartmentEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE SP_DeleteAllDepartmentManagers
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    -- Insert statements for procedure here
        ///	BEGIN TRANSACTION;
        ///	Delete from DepartmentManagers
        ///	COMMIT TRANSACTION
        ///END
        ///GO.
        /// </summary>
        internal static string SP_DeleteAllDepartmentManagers {
            get {
                return ResourceManager.GetString("SP_DeleteAllDepartmentManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE SP_DeleteAllDepartments
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    -- Insert statements for procedure here
        ///	BEGIN TRANSACTION;
        ///	Delete from DepartmentEmployees
        ///	Delete from Departments
        ///	COMMIT TRANSACTION
        ///END
        ///GO
        ///.
        /// </summary>
        internal static string SP_DeleteAllDepartments {
            get {
                return ResourceManager.GetString("SP_DeleteAllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE SP_DeleteAllEmployees
        ///
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    -- Insert statements for procedure here
        ///	BEGIN TRANSACTION;
        ///	Delete from Employees
        ///	COMMIT TRANSACTION
        ///END
        ///GO
        ///.
        /// </summary>
        internal static string SP_DeleteAllEmployees {
            get {
                return ResourceManager.GetString("SP_DeleteAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE SP_DeleteAllEmployeeTitles 
        ///
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    -- Insert statements for procedure here
        ///	BEGIN TRANSACTION;
        ///	Delete from Employees  where EmployeeTitleId in (select t.Id from EmployeeTitles t) 
        ///	Delete from EmployeeTitles
        ///	COMMIT TRANSACTION
        ///END
        ///GO
        ///.
        /// </summary>
        internal static string SP_DeleteAllEmployeeTitles {
            get {
                return ResourceManager.GetString("SP_DeleteAllEmployeeTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SP_DeleteDepartmentEmployees {
            get {
                return ResourceManager.GetString("SP_DeleteDepartmentEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SP_DeleteDepartmentManagers {
            get {
                return ResourceManager.GetString("SP_DeleteDepartmentManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SP_DeleteDepartments {
            get {
                return ResourceManager.GetString("SP_DeleteDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SP_DeleteEmployees {
            get {
                return ResourceManager.GetString("SP_DeleteEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SP_DeleteEmployeeTitles {
            get {
                return ResourceManager.GetString("SP_DeleteEmployeeTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCEDURE [dbo].[SP_InsertDepartmentEmployees]
        ///	-- Add the parameters for the stored procedure here
        ///	@Number int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	DECLARE @cnt INT = 0;
        ///	DECLARE @helpId INT = null;
        ///	DECLARE @helpId2 INT = null;
        ///		DECLARE @VariableDepartments TABLE(
        ///		Id int IDENTITY (1, 1),
        ///    DepartmentId int NULL
        ///);
        ///
        ///		DECLARE @VariableEmployees TABLE(
        ///		Id int IDENTITY (1, 1),
        ///    Emplo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_InsertDepartmentEmployees {
            get {
                return ResourceManager.GetString("SP_InsertDepartmentEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[SP_InsertDepartmentManagers]
        ///	-- Add the parameters for the stored procedure here
        ///	@Number int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	DECLARE @cnt INT = 0;
        ///	DECLARE @helpId INT = null;
        ///	DECLARE @helpId2 INT = null;
        ///		DECLARE @VariableDepartments TABLE(
        ///		Id int IDENTITY (1, 1),
        ///    DepartmentId int NULL
        ///);
        ///
        ///		DECLARE @VariableEmployees TABLE(
        ///		Id int IDENTITY (1, 1),
        ///    Employee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_InsertDepartmentManagers {
            get {
                return ResourceManager.GetString("SP_InsertDepartmentManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[SP_InsertDepartments]
        ///	-- Add the parameters for the stored procedure here
        ///	@Number int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	DECLARE @cnt INT = 0;
        ///
        ///		  WHILE @cnt &lt; @Number
        ///BEGIN
        ///	Insert into Departments (Name) 
        ///	values (&apos;TestDep&apos;);
        ///   SET @cnt = @cnt + 1;
        ///END;
        ///
        ///
        ///
        ///
        ///
        ///END
        ///.
        /// </summary>
        internal static string SP_InsertDepartments {
            get {
                return ResourceManager.GetString("SP_InsertDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[SP_InsertEmployees]
        ///	-- Add the parameters for the stored procedure here
        ///	@Number int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	DECLARE @cnt INT = 0;
        ///	DECLARE @titleId INT = null;
        ///		DECLARE @VariableEmployeeTitles TABLE(
        ///		Id int IDENTITY (1, 1),
        ///    TitleId int NULL
        ///);
        ///    -- Insert statements for procedure here
        ///		Insert into @VariableEmployeeTitles
        ///	    Select Id from EmployeeTitles        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_InsertEmployees {
            get {
                return ResourceManager.GetString("SP_InsertEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[SP_InsertEmployeeTitles]
        ///	-- Add the parameters for the stored procedure here
        ///	@Number int
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///	DECLARE @cnt INT = 0;
        ///
        ///		  WHILE @cnt &lt; @Number
        ///BEGIN
        ///	Insert into EmployeeTitles (Title) 
        ///	values (&apos;TestTitle&apos;);
        ///   SET @cnt = @cnt + 1;
        ///END;
        ///
        ///
        ///
        ///
        ///
        ///END.
        /// </summary>
        internal static string SP_InsertEmployeeTitles {
            get {
                return ResourceManager.GetString("SP_InsertEmployeeTitles", resourceCulture);
            }
        }
    }
}
